[profile.dev]
opt-level = 0
debug = true
lto = false
codegen-units = 256
panic = "unwind"
incremental = true

[profile.dev.package."*"]
opt-level = 0

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false
incremental = false

[profile.release.package."*"]
opt-level = 3

[profile.release-pgo-instrument]
inherits = "release"
debug = true
lto = false
incremental = false

[profile.release-pgo-instrument.package."*"]
opt-level = 3

[profile.release-pgo]
inherits = "release"
incremental = false

[profile.release-pgo.package."*"]
opt-level = 3

[alias]
pgo-instrument = "build --profile release-pgo-instrument"
pgo-build = "build --profile release-pgo"
