name: Cargo Machete

on:
  pull_request:
    branches: "*"
  workflow_dispatch: # 👈 adds manual "Run workflow" button

jobs:
  detect-unused-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Machete
        uses: bnjbvr/cargo-machete@main
